version: "3.8"

services:
  web:
    build: .
    container_name: django-notes-manager
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
