version: "3.8"

services:
  web:
    build: .
    container_name: django-notes-manager
    command: gunicorn --bind 0.0.0.0:8000 notes_manager_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
